const fortunesArray = [
  "A dubious friend may be an enemy in camouflage.",
  "A feather in the hand is better than a bird in the air.",
  "A short pencil is usually better than a long memory.",
  "Accept something that you cannot change, and you will feel better.",
  "Advice, when most needed, is least heeded.",
  "Any decision you have to make tomorrow is a good decision.",
  "It is better to ask twice than to lose yourself once.",
  "Dedicate yourself with a calm mind to the task at hand.",
  "Do not let ambitions overshadow small successes.",
  "Do not be discouraged. Every wrong attempt is another step forward.",
  "Each day, compel yourself to do something you would rather not do.",
  "Every flower blooms in its own sweet time.",
  "Every wise man started out by asking many questions.",
  "Failure is the path of least persistence.",
  "Follow the middle path. Neither extreme will make you happy.",
  "Have a beautiful day.",
  "He who knows he has enough is rich.",
  "If a true sense of value is to be yours it must come through service.",
  "Imagination rules the world.",
  "It is better to deal with problems before they arise.",
  "It takes courage to admit fault.",
  "Love lights up the world.",
  "Put your mind into planning today. Look into the future.",
  "Say hello to others. You will have a happier day.",
  "Share your joys and sorrows with your family.",
  "Strong reasons make strong actions.",
  "The best prediction of the future is the past.",
  "The only people who never fail are those who never try.",
  "The saints are the sinners who keep on trying.",
  "There is no such thing as an ordinary cat.",
  "We first make our habits, and then our habits make us.",
  "You look pretty.",
  "Technology is the art of arranging the world, so we do not notice it.",
  "If you think you can do a thing or think you can not do a thing, you are right.",
  "Mans mind, once stretched by a new idea, never regains its original dimensions.",
  "For the things we have to learn before we can do them, we learn by doing them.",
];
